// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmmposdobssorzcfduvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtbXBvc2RvYnNzb3J6Y2ZkdXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDk3OTMsImV4cCI6MjA2MjgyNTc5M30.cfPoWssxEEJy__11BTIPtinsqxeoOsLQ0sHoJ8ZAc80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);